version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      #登录ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 183631316272.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo npm install completed on `date`
      - npm run build
      - echo npm run build completed on `date`

      - TAG='date "+Y%m%d%H%M%S%"'

      - docker build -t 183631316272.dkr.ecr.ap-northeast-1.amazonaws.com/ecr1028:$TAG ./
      - echo docker build completed on `date`

      - docker push 183631316272.dkr.ecr.ap-northeast-1.amazonaws.com/ecr1028:$TAG
      - echo docker push completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"myhttpd","imageUri":"%s"}]' 183631316272.dkr.ecr.ap-northeast-1.amazonaws.com/ecr1028:$TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json